lang: en
title: Valknar's
copyright: © 2025 Valknar. All rights reserved.
description: Valknar's blog. Coding, Art, and Life.
tagline: Coding, Art, and Life
logo: /assets/img/logo.svg
favicon: /assets/icons/favicon.svg
author:
  # Used by `jekyll-feed`:
  name: Sebastian Krüger
  email: valknar@pivoine.art
  # Used by `jekyll-seo-tag`:
  twitter: bordeaux1981

url: https://pivoine.art
baseurl: ''

exclude:
- packages
- gfx

include:
- _pages
- CNAME

twitter:
  username: bordeaux1981

github:
  username: valknarogg

collections:
  posts:
    output: true
    permalink: /:categories/:slug

accent_image: /assets/bg/hypertown.webp
accent_video: /assets/bg/hypertown.mp4
accent_color: rgb(255, 168, 202)
theme_color: rgb(255,255,255)

menu:
legal:
- title: About
  url: /about
- title: Imprint
  url: /imprint

timezone: Europe/Berlin

featured_categories:
- slug: Palina
  title: Palina
  url: /palina
- slug: Odinsland
  title: Odinsland
  url: /odinsland
- slug: Devilish
  title: Devilish
  url: /devilish
- slug: Souls
  title: Souls
  url: /souls
- slug: Sketches
  title: Sketches
  url: /sketches
- slug: Music
  title: Music
  url: /music

featured_tags:
- slug: Hyperloop
  title: Hyperloop
  url: /hyperloop

lsi: true

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
permalink: pretty

plugins:
- jekyll-default-layout
- jekyll-feed
- jekyll-optional-front-matter
- jekyll-paginate-v2
- jekyll-readme-index
- jekyll-redirect-from
- jekyll-relative-links
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-titles-from-headings
- jekyll-include-cache
- jekyll-last-modified-at

pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: all
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  sort_field: 'date'
  sort_reverse: true

autopages:
  # Site-wide kill switch, disable here and it doesn't run at all
  enabled: false

google_fonts: false

pivoine:
  # Configure the order of complementary content on blog posts
  post_addons: [ about, newsletter, related, random, comments ]

  # Configure the order of complementary content on project pages
  project_addons: [ about, newsletter, other, comments ]

  # Set to `true` if you don't want to show an icon indicating external links
  no_mark_external: true

  # Set to `true` if third party plugins fail to work with dynamically loaded pages
  no_push_state: false

  # Set to `true` if you want to disable the drawer
  no_drawer: false

  # Set to `true` if you don't to use the auto-hiding (JavaScript based) navbar.
  # Note that this will not hide the navbar completely, only replace it with a static one.
  # Use custom css to hide completely, e.g. `#_navbar { display: none }`.
  no_navbar: false

  # Set to true to disable the built-in search functionality.
  # Note that search is disabled during local use to save on build time.
  # Run Jekyll with the `JEKYLL_ENV` environment variable set to `production` to enable.
  no_search: false

  # Set to `true` if you do not want parts of the css inlined in <head/>
  # This will increase site build speed dramatically!
  no_inline_css: false

  # Set to `true` if you don't intend on changing the accent color on a per-page basis. 
  # This will increase site build speed!
  no_page_style: false

  # Code blocks and tables "break" the layout by spanning the full available width.
  # Set this to true if you want them to be the same width as other content.
  no_break_layout: true

  # Set to `true` to disable the dynamic Table of Contents on large screens.
  no_toc: false

  # When set to `true`, will not extend the content in the "third column" on large screens.
  # Instead, all content will remains within the center column.
  # Note that this will not affect the Table of Contents, use `no_toc` instead.
  no_third_column: false

  # Set to `true` if you don't like oversized headlines on large screens.
  no_large_headings: false

  # Set to `true` if you do not want to expose your resume and projects
  # in machine-readable formats.
  no_structured_data: false

  # You can set this to `true` if you don't want to set the `theme-color` meta tag,
  # This only affects the meta tag, not the color specified in the app manifest.
  no_theme_color: false

  # Disable the breadcrumbs above the title
  no_breadcrumbs: false

  # Set to `true` when building with the `--lsi` option.
  # The net effect is to use the Jekyll-provided `site.related_posts` variable.
  use_lsi: true

  # When using Google Analytics, set to `true` to display a cookie notice banner.
  # When enabled, no user-related data will be stored until the user gives consent.
  cookies_banner: false

  # Set to `true` if you would like to add a "Powered by pivoine" link in the footer.
  # Note that this setting has no effect when using the free version.
  advertise: false

  # Buyers of the PRO version can opt to hide all dates from the theme.
  # Frequent consumers of online content will know that nothing devalues a post like
  # seeing an old date. 
  hide_dates: false

  # Similarly, showing last modified date can devalue a post if it is too far in the past.
  hide_last_modified: true

  # Note that dark mode only works in the PRO version of pivoine.
  dark_mode:
    # Set to `true` to always use the dark theme.
    always: false

    # Set to `true` to use the dark theme based on visitors' preference (OS setting).
    dynamic: true

    # Set to `true` to allow visitors to switch between light and dark mode.
    icon: true

  search:
    icon: true

  umami: false

  sound: true

  # ⚡️ DANGER ZONE ⚡️
  # ----------------
  # This is an _experimental_ feature.
  # Only use if you know what Service Workers are and how they can impact your site!
  offline:
    enabled: false
    cache_version: 13
    precache_assets:
    - /assets/img/swipe.svg

optional_front_matter:
  remove_originals: true

readme_index:
  remove_originals: true
  with_frontmatter: true

relative_links:
  collections: true

titles_from_headings:
  strip_title: true
  collections: true

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

sass:
  style: compressed
